### ISSUE TITLE
make a release

### ISSUE THREAD

**Issue by deep-42-thought** [masonicboom/ipscrub#2]
This looks great. I tried it out and it works just as advertised.
Can you please make a release, so I can package it with a more useful version than some development hash?

**Comment by masonicboom** [comment]
Here you go. Released as v1.0.0. Thanks for packaging!

**Comment by masonicboom** [comment]
I'll be happy to link to your package if drop me a link when it's out

**Comment by deep-42-thought** [comment]
ok, it's in the [AUR](https://aur.archlinux.org/packages/nginx-mod-ipscrub/) and my package repository built for [x86_64](https://arch.eckner.net/archlinuxewe/os/x86_64/nginx-mod-ipscrub-1.0.0-1-x86_64.pkg.tar.xz) and for [i686](https://arch.eckner.net/archlinuxewe/os/i686/nginx-mod-ipscrub-1.0.0-1-i686.pkg.tar.xz) (archlinux)

**Comment by masonicboom** [comment]
Linked. Thanks again

**Comment by masonicboom** [comment]
@deep-42-thought could you make a new package? There was a vulnerability in the first version I released (see https://github.com/masonicboom/ipscrub/issues/4). For the moment, I removed the link to your package from the README, so we don't spread the vulnerable version.

There's now a dependency on libbsd—hope that's not too much trouble.

**Comment by deep-42-thought** [comment]
I updated the package.
btw: I get notified about new releases (semi)automatically, so you only need to let me know when you add/remove dependencies :-)

**Comment by masonicboom** [comment]
That's great. Thank you!
